pins:
  clk_pin: 13
  dt_pin: 5
  sw_pin: 6

moode:
  host: localhost
  port: 6600
  connection_timeout: 5  # Timeout in seconds for moode API connection

display:
  icon_dir: "/home/matt/Quoode/src/assets/images"
  default_album_art: "/home/matt/Quoode/src/assets/images/webradio.png"
  loading_gif_path: "/home/matt/Quoode/src/assets/images/Loading.gif"
  logo_path: "/home/matt/Quoode/src/assets/images/logo.png"  # Path relative to project root
  rotation: 2  # Set rotation if needed (0, 90, 180, 270)

  fonts:
    # Playback / Menu / Data
    playback_large:
      path: "/home/matt/Quoode/src/assets/fonts/DSEG7Classic-Light.ttf"
      size: 45
    playback_medium:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 18
    playback_small:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    artist_font:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    song_font:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 14
    data_font:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 10
    menu_font:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    menu_font_bold:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Bold.ttf"
      size: 12

    # Clock fonts (for hours/minutes)
    clock_sans:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 40
    clock_dots:
      path: "/home/matt/Quoode/src/assets/fonts/led_counter-7.ttf"
      size: 40
    clock_digital:
      path: "/home/matt/Quoode/src/assets/fonts/DSEG7Classic-Light.ttf"
      size: 30

    # Smaller date fonts (for optional date line)
    clockdate_sans:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 15
    clockdate_dots:
      path: "/home/matt/Quoode/src/assets/fonts/led_counter-7.ttf"
      size: 15
    clockdate_digital:
      path: "/home/matt/Quoode/src/assets/fonts/DSEG7Classic-Light.ttf"
      size: 10

    # Sample rate / radio usage
    sample_rate:
      path: "/home/matt/Quoode/src/assets/fonts/DSEG7Classic-LightItalic.ttf"
      size: 46
    sample_rate_khz:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    radio_title:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 15
    radio_bitrate:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    volume_small:
      path: "/home/matt/Quoode/src/assets/fonts/OpenSans-Regular.ttf"
      size: 8

  refresh_rate: 60  # Display refresh rate in Hz
  cache_images: true

  preload_images:
    - "/home/matt/Quoode/src/assets/images/screensaver.png"
    - "/home/matt/Quoode/src/assets/images/mpd.png"
    - "/home/matt/Quoode/src/assets/images/clock.png"
    - "/home/matt/Quoode/src/assets/images/default.png"
    - "/home/matt/Quoode/src/assets/images/nas.png"
    - "/home/matt/Quoode/src/assets/images/data.png"
    - "/home/matt/Quoode/src/assets/images/volume.png"
    - "/home/matt/Quoode/src/assets/images/display.png"
    - "/home/matt/Quoode/src/assets/images/webradio.png"

mcp23017_address: 0x20

logging:
  level: "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR
  log_file: "/home/matt/Quoode/quoodeclean.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
